---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-deployment3
  labels:
    app: zomato

spec:
  replicas: 6
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: cont1
          image: shaikmustafa/dm
          ports:
            - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3   


